//! The deterministic strict-TypeScript client generator.
//!
//! [`generate_client`] renders one `client.mts` from a reconstructed wire
//! [`Interface`]: one named `async` method per export, exact structural transfer
//! types, and per-signature encoder/decoder pipelines composed from the pinned
//! supervision module's combinators (which perform the runtime validation
//! mirroring the wire grammar). The output is a pure function of the interface
//! and the export directory — no clock, path, environment, or map-order input —
//! so stable inputs yield byte-identical output; a drift test freezes a golden.
//!
//! Type projection (the transfer graph):
//!
//! | transfer type | TypeScript |
//! |---|---|
//! | unit (return only) | `void` |
//! | int | `bigint` (a JS `number` is not 64-bit exact) |
//! | bool | `boolean` |
//! | text | `string` |
//! | bytes | `Uint8Array` (0x-hex on the wire) |
//! | date / instant / duration | `string` in the canonical text spelling |
//! | `T?` | `T \| null` |
//! | product | inline `{ field: T; sparse?: T }` |
//! | sum | inline `{ member: "name"; payload: [..] } \| ...` union |
//! | `List<T>` | `Array<T>` |
//! | `Map<K, V>` | `Array<[K, V]>` (ordered pairs, never a JS object) |
//! | `Id(^root)` | `{ readonly root: "root"; readonly key: [..] }` (branded handle) |
//!
//! Method names come from the compiler's export directory: the bare item name
//! when it is unique, `module_item` (with `::` and `.` folded to `_`) when two
//! modules export the same item, and a `call_` prefix when the result would
//! collide with a `Client` member or a JavaScript reserved word.

use marrow_image::{ExportId, FunctionDescriptor, ImageId, Interface, InterfaceId, TransferType};

/// One export's naming row: its id and its `module`/`item` spelling from the
/// compiler's export directory.
pub(crate) struct ExportName {
    pub(crate) id: ExportId,
    pub(crate) module: String,
    pub(crate) item: String,
}

/// Render the complete `client.mts` source. `image_id` is the exact image identity
/// the native attached-session (`--store`) launch proves back; the storeless launch
/// proves the interface identity instead.
pub(crate) fn generate_client(
    interface: &Interface,
    names: &[ExportName],
    image_id: ImageId,
) -> String {
    let mut out = String::new();
    header(&mut out, interface.interface_id(), image_id);
    let methods: Vec<String> = interface
        .descriptors()
        .iter()
        .map(|descriptor| method(descriptor, names))
        .collect();
    out.push_str("export class Client {\n");
    // Erasable-syntax-only TypeScript: no parameter properties, so the client
    // runs directly under Node's default type stripping.
    out.push_str("  private readonly session: M.Session;\n\n");
    out.push_str("  private constructor(session: M.Session) {\n");
    out.push_str("    this.session = session;\n  }\n\n");
    out.push_str(
        "  /** Launch the runner and open one authenticated session; refuses a runner\n   * whose served identity is not the one this client was generated for. A\n   * storeless launch proves the interface identity; a native attached-session\n   * launch (`options.store` set) proves the exact image identity. */\n",
    );
    out.push_str("  static async launch(options: M.LaunchOptions): Promise<Client> {\n");
    out.push_str("    const expected = options.store === undefined ? INTERFACE_ID : IMAGE_ID;\n");
    out.push_str(
        "    const session = await M.launch({ ...options, expectedIdentity: expected });\n",
    );
    out.push_str("    return new Client(session);\n  }\n\n");
    out.push_str("  /** Hang up and observe the runner's exit; rejects if it is unconfirmed. */\n");
    out.push_str("  close(): Promise<void> {\n    return this.session.close();\n  }\n\n");
    out.push_str("  /** Immediate fail-closed shutdown; outstanding calls classify as lost. */\n");
    out.push_str("  terminate(): void {\n    this.session.terminate();\n  }\n");
    for method in &methods {
        out.push('\n');
        out.push_str(method);
    }
    out.push_str("}\n");
    out
}

fn header(out: &mut String, id: InterfaceId, image_id: ImageId) {
    out.push_str("// Generated by `marrow client typescript`. Do not edit.\n");
    out.push_str("//\n");
    out.push_str("// One named method per export; every value crossing the wire is validated\n");
    out.push_str("// against the export's verified signature here and again by the runner.\n");
    out.push_str("// This client and its runner are a matched pair, pinned by INTERFACE_ID\n");
    out.push_str("// (storeless) and IMAGE_ID (the native attached-session `--store` launch).\n");
    out.push_str("\nimport * as M from \"./marrow-supervisor.mjs\";\n\n");
    out.push_str("/** The identity of the wire interface this client was generated for. */\n");
    out.push_str(&format!(
        "export const INTERFACE_ID = \"{}\";\n\n",
        id.to_hex()
    ));
    out.push_str("/** The exact image identity a native attached-session launch proves back. */\n");
    out.push_str(&format!(
        "export const IMAGE_ID = \"{}\";\n\n",
        image_id.to_hex()
    ));
}

/// Render one export's method.
fn method(descriptor: &FunctionDescriptor, names: &[ExportName]) -> String {
    let name = method_name(descriptor, names);
    let doc = names
        .iter()
        .find(|row| row.id == descriptor.id())
        .map(|row| format!("{}.{}", row.module, row.item))
        .unwrap_or_else(|| descriptor.id().to_hex());

    let params: Vec<String> = descriptor
        .params()
        .iter()
        .enumerate()
        .map(|(i, ty)| format!("arg{i}: {}", ts_type(ty)))
        .collect();
    let args: Vec<String> = descriptor
        .params()
        .iter()
        .enumerate()
        .map(|(i, ty)| format!("{}(arg{i})", codec(Direction::Encode, ty)))
        .collect();
    let ret = descriptor.ret();
    let ret_ts = ts_type(ret);

    let mut out = String::new();
    out.push_str(&format!("  /** `{doc}` */\n"));
    out.push_str(&format!(
        "  async {name}({}): Promise<{ret_ts}> {{\n",
        params.join(", ")
    ));
    let call = format!(
        "await this.session.call(\"{}\", [{}], {})",
        descriptor.id().to_hex(),
        args.join(", "),
        codec(Direction::Decode, ret),
    );
    out.push_str(&format!(
        "    return {};\n",
        decode_expr(ret, &call, &ret_ts)
    ));
    out.push_str("  }\n");
    out
}

/// `Client` members and JavaScript reserved words a method may not shadow.
const RESERVED: &[&str] = &[
    "constructor",
    "close",
    "terminate",
    "launch",
    "session",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "new",
    "null",
    "return",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

fn method_name(descriptor: &FunctionDescriptor, names: &[ExportName]) -> String {
    let Some(row) = names.iter().find(|row| row.id == descriptor.id()) else {
        // No directory row (a caller-assembled interface): fall back to the id.
        return format!("call_{}", &descriptor.id().to_hex()[..16]);
    };
    let ambiguous = names.iter().filter(|other| other.item == row.item).count() > 1;
    let base = if ambiguous {
        format!("{}_{}", sanitize(&row.module), sanitize(&row.item))
    } else {
        sanitize(&row.item)
    };
    if RESERVED.contains(&base.as_str()) {
        format!("call_{base}")
    } else {
        base
    }
}

/// Fold a Marrow path spelling into a JavaScript identifier.
fn sanitize(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for (i, ch) in name.chars().enumerate() {
        let valid = ch.is_ascii_alphanumeric() || ch == '_' || ch == '$';
        let valid_start = ch.is_ascii_alphabetic() || ch == '_' || ch == '$';
        if (i == 0 && valid_start) || (i > 0 && valid) {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    out
}

/// The TypeScript type of one transfer type.
fn ts_type(ty: &TransferType) -> String {
    match ty {
        TransferType::Unit => "void".to_string(),
        TransferType::Scalar(scalar) => scalar_ts(*scalar).to_string(),
        TransferType::Optional(inner) => format!("{} | null", ts_type(inner)),
        TransferType::Product(fields) => {
            let mut out = String::from("{ ");
            for (i, field) in fields.iter().enumerate() {
                if i > 0 {
                    out.push_str("; ");
                }
                out.push_str(&field.name);
                if !field.required {
                    out.push('?');
                }
                out.push_str(": ");
                out.push_str(&ts_type(&field.ty));
            }
            out.push_str(" }");
            out
        }
        TransferType::Sum(variants) => variants
            .iter()
            .map(|variant| {
                let payload: Vec<String> = variant.payload.iter().map(ts_type).collect();
                format!(
                    "{{ member: \"{}\"; payload: [{}] }}",
                    variant.name,
                    payload.join(", ")
                )
            })
            .collect::<Vec<_>>()
            .join(" | "),
        TransferType::List(elem) => format!("Array<{}>", ts_type(elem)),
        // An ordered map crosses as an array of `[key, value]` pairs, never a JS
        // object, so a non-string key and entry order both survive.
        TransferType::Map(key, value) => {
            format!("Array<[{}, {}]>", ts_type(key), ts_type(value))
        }
        // An entry identity is a branded handle carrying its root name and key tuple,
        // so the client cannot pass an `Id(^a)` where an `Id(^b)` is expected.
        TransferType::Identity { root, keys } => {
            let key_tuple: Vec<&str> = keys.iter().map(|s| scalar_ts(*s)).collect();
            format!(
                "{{ readonly root: \"{root}\"; readonly key: [{}] }}",
                key_tuple.join(", ")
            )
        }
    }
}

fn scalar_ts(scalar: marrow_image::Scalar) -> &'static str {
    match scalar {
        marrow_image::Scalar::Int => "bigint",
        marrow_image::Scalar::Bool => "boolean",
        marrow_image::Scalar::Text => "string",
        marrow_image::Scalar::Bytes => "Uint8Array",
        // Temporal values cross as their canonical text spellings.
        marrow_image::Scalar::Date
        | marrow_image::Scalar::Instant
        | marrow_image::Scalar::Duration => "string",
    }
}

/// Which way a codec pipeline carries a value across the wire. The pinned supervision
/// module names each combinator by direction letter: `M.eInt` encodes, `M.dInt` decodes.
#[derive(Clone, Copy)]
enum Direction {
    Encode,
    Decode,
}

impl Direction {
    fn letter(self) -> char {
        match self {
            Self::Encode => 'e',
            Self::Decode => 'd',
        }
    }
}

/// The codec pipeline expression for one transfer type in one direction: a combinator
/// value from the pinned supervision module, applied by the caller. Encoding and
/// decoding compose the same structure, so one walk serves both.
fn codec(direction: Direction, ty: &TransferType) -> String {
    let d = direction.letter();
    match ty {
        // Unit is not an argument type; a verified signature never carries one.
        TransferType::Unit => "M.dUnit".to_string(),
        TransferType::Scalar(scalar) => scalar_codec(direction, *scalar),
        TransferType::Optional(inner) => format!("M.{d}Opt({})", codec(direction, inner)),
        TransferType::Product(fields) => {
            let rows: Vec<String> = fields
                .iter()
                .map(|field| {
                    format!(
                        "[\"{}\", {}, {}]",
                        field.name,
                        field.required,
                        codec(direction, &field.ty)
                    )
                })
                .collect();
            format!("M.{d}Record([{}])", rows.join(", "))
        }
        TransferType::Sum(variants) => {
            let rows: Vec<String> = variants
                .iter()
                .map(|variant| {
                    let leaves: Vec<String> = variant
                        .payload
                        .iter()
                        .map(|ty| codec(direction, ty))
                        .collect();
                    format!("[\"{}\", [{}]]", variant.name, leaves.join(", "))
                })
                .collect();
            format!("M.{d}Sum([{}])", rows.join(", "))
        }
        TransferType::List(elem) => format!("M.{d}List({})", codec(direction, elem)),
        TransferType::Map(key, value) => {
            format!(
                "M.{d}Map({}, {})",
                codec(direction, key),
                codec(direction, value)
            )
        }
        TransferType::Identity { root, keys } => {
            let key_codecs: Vec<String> =
                keys.iter().map(|s| scalar_codec(direction, *s)).collect();
            format!("M.{d}Id(\"{root}\", [{}])", key_codecs.join(", "))
        }
    }
}

/// Whether a decoder already returns exactly its `ts_type`, so the `as` cast is
/// redundant. A structural product/sum decoder returns `unknown` and the identity
/// decoder returns a loosely-typed `{ root; key }`, so those need the cast; a scalar,
/// unit, and any optional/list/map composed only of precise decoders are already
/// exact (the generic `dOpt`/`dList`/`dMap` combinators carry their element types).
fn decoder_is_precise(ty: &TransferType) -> bool {
    match ty {
        TransferType::Unit | TransferType::Scalar(_) => true,
        TransferType::Optional(inner) => decoder_is_precise(inner),
        TransferType::List(elem) => decoder_is_precise(elem),
        TransferType::Map(key, value) => decoder_is_precise(key) && decoder_is_precise(value),
        TransferType::Product(_) | TransferType::Sum(_) | TransferType::Identity { .. } => false,
    }
}

/// The full decode expression for a return value. A precise decoder is emitted bare;
/// one that returns `unknown` (or the loosely-typed identity handle) is cast to its
/// exact structural type.
fn decode_expr(ret: &TransferType, decoded: &str, ret_ts: &str) -> String {
    if decoder_is_precise(ret) {
        decoded.to_string()
    } else {
        format!("{decoded} as {ret_ts}")
    }
}

fn scalar_codec(direction: Direction, scalar: marrow_image::Scalar) -> String {
    let name = match scalar {
        marrow_image::Scalar::Int => "Int",
        marrow_image::Scalar::Bool => "Bool",
        marrow_image::Scalar::Text => "Text",
        marrow_image::Scalar::Bytes => "Bytes",
        marrow_image::Scalar::Date => "Date",
        marrow_image::Scalar::Instant => "Instant",
        marrow_image::Scalar::Duration => "Duration",
    };
    format!("M.{}{name}", direction.letter())
}

/// The pinned supervision module, emitted verbatim beside the generated client.
pub(crate) const SUPERVISOR_MJS: &str = include_str!("supervisor/marrow-supervisor.mjs");

/// The pinned supervision module's type declarations.
pub(crate) const SUPERVISOR_DTS: &str = include_str!("supervisor/marrow-supervisor.d.mts");
