//! The deterministic strict-TypeScript client generator.
//!
//! [`generate_client`] renders one `client.mts` from a reconstructed wire
//! [`Interface`]: one named `async` method per export, exact structural transfer
//! types, and per-signature encoder/decoder pipelines composed from the pinned
//! supervision module's combinators (which perform the runtime validation
//! mirroring the wire grammar). The output is a pure function of the interface
//! and the export directory — no clock, path, environment, or map-order input —
//! so stable inputs yield byte-identical output; a drift test freezes a golden.
//!
//! Type projection (the G00a transfer graph):
//!
//! | transfer type | TypeScript |
//! |---|---|
//! | unit (return only) | `void` |
//! | int | `bigint` (a JS `number` is not 64-bit exact) |
//! | bool | `boolean` |
//! | text | `string` |
//! | bytes | `Uint8Array` (0x-hex on the wire) |
//! | date / instant / duration | `string` in the canonical text spelling |
//! | `T?` | `T \| null` |
//! | product | inline `{ field: T; sparse?: T }` |
//! | sum | inline `{ member: "name"; payload: [..] } \| ...` union |
//!
//! Method names come from the compiler's export directory: the bare item name
//! when it is unique, `module_item` (with `::` and `.` folded to `_`) when two
//! modules export the same item, and a `call_` prefix when the result would
//! collide with a `Client` member or a JavaScript reserved word.

use marrow_image::{FunctionDescriptor, Interface, InterfaceId, TransferType};

/// One export's naming row: its 32-byte id and its `module`/`item` spelling from
/// the compiler's export directory.
pub(crate) struct ExportName {
    pub(crate) id: [u8; 32],
    pub(crate) module: String,
    pub(crate) item: String,
}

/// Render the complete `client.mts` source. `image_id` is the exact 32-byte
/// image identity the native attached-session (`--store`) launch proves back;
/// the storeless launch proves the interface identity instead.
pub(crate) fn generate_client(
    interface: &Interface,
    names: &[ExportName],
    image_id: [u8; 32],
) -> String {
    let mut out = String::new();
    header(&mut out, interface.interface_id(), image_id);
    let methods: Vec<String> = interface
        .descriptors()
        .iter()
        .map(|descriptor| method(descriptor, names))
        .collect();
    out.push_str("export class Client {\n");
    // Erasable-syntax-only TypeScript: no parameter properties, so the client
    // runs directly under Node's default type stripping.
    out.push_str("  private readonly session: M.Session;\n\n");
    out.push_str("  private constructor(session: M.Session) {\n");
    out.push_str("    this.session = session;\n  }\n\n");
    out.push_str(
        "  /** Launch the runner and open one authenticated session; refuses a runner\n   * whose served identity is not the one this client was generated for. A\n   * storeless launch proves the interface identity; a native attached-session\n   * launch (`options.store` set) proves the exact image identity. */\n",
    );
    out.push_str("  static async launch(options: M.LaunchOptions): Promise<Client> {\n");
    out.push_str("    const session = await M.launch(options);\n");
    out.push_str(
        "    const expected = options.store === undefined ? INTERFACE_ID : IMAGE_ID;\n",
    );
    out.push_str("    if (session.interfaceId !== expected) {\n");
    out.push_str("      session.terminate();\n");
    out.push_str(
        "      throw new Error(`identity mismatch: runner serves ${session.interfaceId}`);\n",
    );
    out.push_str("    }\n    return new Client(session);\n  }\n\n");
    out.push_str("  /** Hang up and wait for the runner to exit. */\n");
    out.push_str("  async close(): Promise<void> {\n    await this.session.close();\n  }\n\n");
    out.push_str("  /** Immediate fail-closed shutdown; outstanding calls classify as lost. */\n");
    out.push_str("  terminate(): void {\n    this.session.terminate();\n  }\n");
    for method in &methods {
        out.push('\n');
        out.push_str(method);
    }
    out.push_str("}\n");
    out
}

fn header(out: &mut String, id: InterfaceId, image_id: [u8; 32]) {
    out.push_str("// Generated by `marrow client typescript`. Do not edit.\n");
    out.push_str("//\n");
    out.push_str("// One named method per export; every value crossing the wire is validated\n");
    out.push_str("// against the export's verified signature here and again by the runner.\n");
    out.push_str("// This client and its runner are a matched pair, pinned by INTERFACE_ID\n");
    out.push_str("// (storeless) and IMAGE_ID (the native attached-session `--store` launch).\n");
    out.push_str("\nimport * as M from \"./marrow-supervisor.mjs\";\n\n");
    out.push_str("/** The identity of the wire interface this client was generated for. */\n");
    out.push_str(&format!(
        "export const INTERFACE_ID = \"{}\";\n\n",
        id.to_hex()
    ));
    out.push_str(
        "/** The exact image identity a native attached-session launch proves back. */\n",
    );
    let image_hex: String = image_id.iter().map(|b| format!("{b:02x}")).collect();
    out.push_str(&format!("export const IMAGE_ID = \"{image_hex}\";\n\n"));
}

/// Render one export's method.
fn method(descriptor: &FunctionDescriptor, names: &[ExportName]) -> String {
    let name = method_name(descriptor, names);
    let doc = names
        .iter()
        .find(|row| &row.id == descriptor.id().bytes())
        .map(|row| format!("{}.{}", row.module, row.item))
        .unwrap_or_else(|| descriptor_hex(descriptor));

    let params: Vec<String> = descriptor
        .params()
        .iter()
        .enumerate()
        .map(|(i, ty)| format!("arg{i}: {}", ts_type(ty)))
        .collect();
    let args: Vec<String> = descriptor
        .params()
        .iter()
        .enumerate()
        .map(|(i, ty)| format!("{}(arg{i})", encoder(ty)))
        .collect();
    let ret = descriptor.ret();
    let ret_ts = ts_type_return(ret);

    let mut out = String::new();
    out.push_str(&format!("  /** `{doc}` */\n"));
    out.push_str(&format!(
        "  async {name}({}): Promise<{ret_ts}> {{\n",
        params.join(", ")
    ));
    out.push_str(&format!(
        "    const data = await this.session.call(\"{}\", [{}]);\n",
        descriptor_hex(descriptor),
        args.join(", ")
    ));
    out.push_str(&format!(
        "    return {};\n",
        decode_expr(ret, "data", &ret_ts)
    ));
    out.push_str("  }\n");
    out
}

fn descriptor_hex(descriptor: &FunctionDescriptor) -> String {
    let mut hex = String::with_capacity(64);
    for byte in descriptor.id().bytes() {
        hex.push(char::from_digit(u32::from(byte >> 4), 16).expect("hex nibble"));
        hex.push(char::from_digit(u32::from(byte & 0xf), 16).expect("hex nibble"));
    }
    hex
}

/// `Client` members and JavaScript reserved words a method may not shadow.
const RESERVED: &[&str] = &[
    "constructor",
    "close",
    "terminate",
    "launch",
    "session",
    "await",
    "break",
    "case",
    "catch",
    "class",
    "const",
    "continue",
    "debugger",
    "default",
    "delete",
    "do",
    "else",
    "enum",
    "export",
    "extends",
    "false",
    "finally",
    "for",
    "function",
    "if",
    "import",
    "in",
    "instanceof",
    "new",
    "null",
    "return",
    "super",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "var",
    "void",
    "while",
    "with",
    "yield",
];

fn method_name(descriptor: &FunctionDescriptor, names: &[ExportName]) -> String {
    let Some(row) = names.iter().find(|row| &row.id == descriptor.id().bytes()) else {
        // No directory row (a caller-assembled interface): fall back to the id.
        return format!("call_{}", &descriptor_hex(descriptor)[..16]);
    };
    let ambiguous = names.iter().filter(|other| other.item == row.item).count() > 1;
    let base = if ambiguous {
        format!("{}_{}", sanitize(&row.module), sanitize(&row.item))
    } else {
        sanitize(&row.item)
    };
    if RESERVED.contains(&base.as_str()) {
        format!("call_{base}")
    } else {
        base
    }
}

/// Fold a Marrow path spelling into a JavaScript identifier.
fn sanitize(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    for (i, ch) in name.chars().enumerate() {
        let valid = ch.is_ascii_alphanumeric() || ch == '_' || ch == '$';
        let valid_start = ch.is_ascii_alphabetic() || ch == '_' || ch == '$';
        if (i == 0 && valid_start) || (i > 0 && valid) {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    out
}

/// The TypeScript type of one transfer type.
fn ts_type(ty: &TransferType) -> String {
    match ty {
        TransferType::Unit => "void".to_string(),
        TransferType::Scalar(scalar) => scalar_ts(*scalar).to_string(),
        TransferType::Optional(inner) => format!("{} | null", ts_type(inner)),
        TransferType::Product(fields) => {
            let mut out = String::from("{ ");
            for (i, field) in fields.iter().enumerate() {
                if i > 0 {
                    out.push_str("; ");
                }
                out.push_str(&field.name);
                if !field.required {
                    out.push('?');
                }
                out.push_str(": ");
                out.push_str(&ts_type(&field.ty));
            }
            out.push_str(" }");
            out
        }
        TransferType::Sum(variants) => variants
            .iter()
            .map(|variant| {
                let payload: Vec<String> = variant.payload.iter().map(ts_type).collect();
                format!(
                    "{{ member: \"{}\"; payload: [{}] }}",
                    variant.name,
                    payload.join(", ")
                )
            })
            .collect::<Vec<_>>()
            .join(" | "),
    }
}

fn ts_type_return(ty: &TransferType) -> String {
    ts_type(ty)
}

fn scalar_ts(scalar: marrow_image::Scalar) -> &'static str {
    match scalar {
        marrow_image::Scalar::Int => "bigint",
        marrow_image::Scalar::Bool => "boolean",
        marrow_image::Scalar::Text => "string",
        marrow_image::Scalar::Bytes => "Uint8Array",
        // Temporal values cross as their canonical text spellings.
        marrow_image::Scalar::Date
        | marrow_image::Scalar::Instant
        | marrow_image::Scalar::Duration => "string",
    }
}

/// The encoder pipeline expression for one transfer type (a combinator value
/// from the pinned supervision module, applied by the caller).
fn encoder(ty: &TransferType) -> String {
    match ty {
        // Unit is not an argument type; a verified signature never carries one.
        TransferType::Unit => "M.dUnit".to_string(),
        TransferType::Scalar(scalar) => scalar_codec("e", *scalar),
        TransferType::Optional(inner) => format!("M.eOpt({})", encoder(inner)),
        TransferType::Product(fields) => {
            let rows: Vec<String> = fields
                .iter()
                .map(|field| {
                    format!(
                        "[\"{}\", {}, {}]",
                        field.name,
                        field.required,
                        encoder(&field.ty)
                    )
                })
                .collect();
            format!("M.eRecord([{}])", rows.join(", "))
        }
        TransferType::Sum(variants) => {
            let rows: Vec<String> = variants
                .iter()
                .map(|variant| {
                    let leaves: Vec<String> = variant.payload.iter().map(encoder).collect();
                    format!("[\"{}\", [{}]]", variant.name, leaves.join(", "))
                })
                .collect();
            format!("M.eSum([{}])", rows.join(", "))
        }
    }
}

/// The decoder pipeline expression for one transfer type.
fn decoder(ty: &TransferType) -> String {
    match ty {
        TransferType::Unit => "M.dUnit".to_string(),
        TransferType::Scalar(scalar) => scalar_codec("d", *scalar),
        TransferType::Optional(inner) => format!("M.dOpt({})", decoder(inner)),
        TransferType::Product(fields) => {
            let rows: Vec<String> = fields
                .iter()
                .map(|field| {
                    format!(
                        "[\"{}\", {}, {}]",
                        field.name,
                        field.required,
                        decoder(&field.ty)
                    )
                })
                .collect();
            format!("M.dRecord([{}])", rows.join(", "))
        }
        TransferType::Sum(variants) => {
            let rows: Vec<String> = variants
                .iter()
                .map(|variant| {
                    let leaves: Vec<String> = variant.payload.iter().map(decoder).collect();
                    format!("[\"{}\", [{}]]", variant.name, leaves.join(", "))
                })
                .collect();
            format!("M.dSum([{}])", rows.join(", "))
        }
    }
}

/// The full decode expression for a return value. A structural decoder returns
/// `unknown`, so a product/sum return is cast to its exact structural type; a
/// scalar decoder is already exact.
fn decode_expr(ret: &TransferType, data: &str, ret_ts: &str) -> String {
    match ret {
        TransferType::Unit | TransferType::Scalar(_) => format!("{}({data})", decoder(ret)),
        TransferType::Optional(inner) if matches!(**inner, TransferType::Scalar(_)) => {
            format!("{}({data})", decoder(ret))
        }
        _ => format!("{}({data}) as {ret_ts}", decoder(ret)),
    }
}

fn scalar_codec(direction: &str, scalar: marrow_image::Scalar) -> String {
    let name = match scalar {
        marrow_image::Scalar::Int => "Int",
        marrow_image::Scalar::Bool => "Bool",
        marrow_image::Scalar::Text => "Text",
        marrow_image::Scalar::Bytes => "Bytes",
        marrow_image::Scalar::Date => "Date",
        marrow_image::Scalar::Instant => "Instant",
        marrow_image::Scalar::Duration => "Duration",
    };
    format!("M.{direction}{name}")
}

/// The pinned supervision module, emitted verbatim beside the generated client.
pub(crate) const SUPERVISOR_MJS: &str = include_str!("supervisor/marrow-supervisor.mjs");

/// The pinned supervision module's type declarations.
pub(crate) const SUPERVISOR_DTS: &str = include_str!("supervisor/marrow-supervisor.d.mts");
