// Generated by `marrow client typescript`. Do not edit.
//
// One named method per export; every value crossing the wire is validated
// against the export's verified signature here and again by the runner.
// This client and its runner are a matched pair, pinned by INTERFACE_ID
// (storeless) and IMAGE_ID (the native attached-session `--store` launch).

import * as M from "./marrow-supervisor.mjs";

/** The identity of the wire interface this client was generated for. */
export const INTERFACE_ID = "1b7824af5eca288fa9aeb8f92b69c9cb5111bdba79aebe61b002ff63a72cad6f";

/** The exact image identity a native attached-session launch proves back. */
export const IMAGE_ID = "090b9ae94f4bbbd84754121e672730a98d35db7b16a3c29c1f88a89aed84f20f";

export class Client {
  private readonly session: M.Session;

  private constructor(session: M.Session) {
    this.session = session;
  }

  /** Launch the runner and open one authenticated session; refuses a runner
   * whose served identity is not the one this client was generated for. A
   * storeless launch proves the interface identity; a native attached-session
   * launch (`options.store` set) proves the exact image identity. */
  static async launch(options: M.LaunchOptions): Promise<Client> {
    const session = await M.launch(options);
    const expected = options.store === undefined ? INTERFACE_ID : IMAGE_ID;
    if (session.interfaceId !== expected) {
      session.terminate();
      throw new Error(`identity mismatch: runner serves ${session.interfaceId}`);
    }
    return new Client(session);
  }

  /** Hang up and wait for the runner to exit. */
  async close(): Promise<void> {
    await this.session.close();
  }

  /** Immediate fail-closed shutdown; outstanding calls classify as lost. */
  terminate(): void {
    this.session.terminate();
  }

  /** `main.add` */
  async add(arg0: bigint, arg1: bigint): Promise<bigint> {
    const data = await this.session.call("615264168892c10801e5f5bb16a3496738f41acf72b74e3edd9f20a6725fedbe", [M.eInt(arg0), M.eInt(arg1)]);
    return M.dInt(data);
  }

  /** `main.ping` */
  async ping(): Promise<void> {
    const data = await this.session.call("64f416543f8043012160edb9a7154b2c97ef4424848b54f01f22e7ba1cb79389", []);
    return M.dUnit(data);
  }

  /** `main.echoAsset` */
  async echoAsset(arg0: { label: string; details: { count: bigint } }): Promise<{ label: string; details: { count: bigint } }> {
    const data = await this.session.call("6983ed0642ac588503184f3c6979b421ba8502a3a27ff4b696c97bf47d308d90", [M.eRecord([["label", true, M.eText], ["details", true, M.eRecord([["count", true, M.eInt]])]])(arg0)]);
    return M.dRecord([["label", true, M.dText], ["details", true, M.dRecord([["count", true, M.dInt]])]])(data) as { label: string; details: { count: bigint } };
  }

  /** `main.grow` */
  async grow(arg0: { member: "dot"; payload: [] } | { member: "circle"; payload: [bigint] }): Promise<{ member: "dot"; payload: [] } | { member: "circle"; payload: [bigint] }> {
    const data = await this.session.call("96102f6d3ce812b6744eca135e0f976a1c7bd4ca448d08cbf98ee546aaca379b", [M.eSum([["dot", []], ["circle", [M.eInt]]])(arg0)]);
    return M.dSum([["dot", []], ["circle", [M.dInt]]])(data) as { member: "dot"; payload: [] } | { member: "circle"; payload: [bigint] };
  }

  /** `main.shift` */
  async shift(arg0: { x: bigint; y: bigint }, arg1: bigint): Promise<{ x: bigint; y: bigint }> {
    const data = await this.session.call("dc5ecfdb00cd260eb04d8c1e12af4784ae4a9de09ef73c18439bec7ec3635b47", [M.eRecord([["x", true, M.eInt], ["y", true, M.eInt]])(arg0), M.eInt(arg1)]);
    return M.dRecord([["x", true, M.dInt], ["y", true, M.dInt]])(data) as { x: bigint; y: bigint };
  }
}
