use crate::support;
use crate::support_surface::{
    create_descriptor, create_field_catalog_id, route_by_alias, spawn_surface_server_with_args,
};

use serde_json::Value;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use support::{marrow, temp_project, temp_project_uncommitted, write};

const CLIENT_SURFACE_SOURCE: &str = "module app\n\
\n\
resource Book\n\
\x20\x20\x20\x20required title: string\n\
\x20\x20\x20\x20author: string\n\
store ^books(id: int): Book\n\
\x20\x20\x20\x20index byAuthor(author, id)\n\
\n\
pub fn seed()\n\
\x20\x20\x20\x20var book: Book\n\
\x20\x20\x20\x20book.title = \"Dune\"\n\
\x20\x20\x20\x20book.author = \"Frank Herbert\"\n\
\x20\x20\x20\x20var sequel: Book\n\
\x20\x20\x20\x20sequel.title = \"Dune Messiah\"\n\
\x20\x20\x20\x20sequel.author = \"Frank Herbert\"\n\
\x20\x20\x20\x20transaction\n\
\x20\x20\x20\x20\x20\x20\x20\x20^books(1) = book\n\
\x20\x20\x20\x20\x20\x20\x20\x20^books(2) = sequel\n\
\n\
pub fn retitle(id: int, title: string): string\n\
\x20\x20\x20\x20transaction\n\
\x20\x20\x20\x20\x20\x20\x20\x20^books(id).title = title\n\
\x20\x20\x20\x20return title\n\
\n\
pub fn describe(id: int): string\n\
\x20\x20\x20\x20return (^books(id).title ?? \"\") + \"|\" + (^books(id).author ?? \"\")\n\
\n\
surface Books from ^books\n\
\x20\x20\x20\x20fields title, author\n\
\x20\x20\x20\x20create title, author\n\
\x20\x20\x20\x20update author\n\
\x20\x20\x20\x20delete\n\
\x20\x20\x20\x20collection ^books.byAuthor as byAuthor\n\
\x20\x20\x20\x20action retitle\n\
\x20\x20\x20\x20read describe\n";

#[test]
fn client_typescript_uses_lock_projection_when_store_is_absent() {
    let root = temp_project("surface-client-typescript", |root| {
        write(root, "marrow.json", support::native_config());
        write(root, "src/app.mw", CLIENT_SURFACE_SOURCE);
    });
    let seed = marrow(&["run", "--entry", "app::seed", root.to_str().unwrap()]);
    assert_eq!(seed.status.code(), Some(0), "seed: {seed:?}");
    let store_path = root.join(".data/marrow.redb");
    assert!(store_path.exists(), "fixture should have seeded a store");
    fs::remove_file(&store_path).expect("remove store file");

    let output = marrow(&[
        "client",
        "typescript",
        root.to_str().expect("project path utf8"),
    ]);

    assert_eq!(output.status.code(), Some(0), "{output:?}");
    assert!(output.stderr.is_empty(), "{output:?}");
    let stdout = String::from_utf8(output.stdout).expect("stdout utf8");
    assert!(stdout.contains("export function createClient"), "{stdout}");
    assert!(!stdout.contains("createMarrowSurfaceClient"), "{stdout}");
    assert!(
        stdout.contains("// Generated by marrow — do not edit."),
        "{stdout}"
    );
    assert!(
        stdout.contains("// marrow-surface-digest: sha256:"),
        "{stdout}"
    );
    assert!(stdout.contains("\"app\""), "{stdout}");
    assert!(stdout.contains("\"Books\""), "{stdout}");
    assert!(stdout.contains("/surface/v1/create/"), "{stdout}");
    assert!(stdout.contains("/surface/v1/delete/"), "{stdout}");
    assert!(stdout.contains("Number.isSafeInteger"), "{stdout}");
    assert!(
        !store_path.exists(),
        "client generation must not recreate the native store"
    );
}

#[test]
fn client_typescript_uses_active_computed_read_route_tags() {
    let root = temp_project("surface-client-typescript-computed-read-tag", |root| {
        write(root, "marrow.json", support::native_config());
        write(root, "src/app.mw", CLIENT_SURFACE_SOURCE);
    });
    let seed = marrow(&["run", "--entry", "app::seed", root.to_str().unwrap()]);
    assert_eq!(seed.status.code(), Some(0), "seed: {seed:?}");

    let check = marrow(&["check", "--format", "json", root.to_str().unwrap()]);
    assert_eq!(check.status.code(), Some(0), "check: {check:?}");
    let report = support::json(check.stdout);
    let route = route_by_alias(&report, "describe");
    fs::remove_file(root.join("marrow.lock")).expect("remove committed lock");

    let client = marrow(&[
        "client",
        "typescript",
        root.to_str().expect("project path utf8"),
    ]);
    assert_eq!(client.status.code(), Some(0), "client: {client:?}");
    let stdout = String::from_utf8(client.stdout).expect("client stdout utf8");
    assert!(
        stdout.contains(&format!("\"operation_tag\": {:?}", route.operation_tag)),
        "generated client must use active computed-read operation tag {}; client:\n{stdout}",
        route.operation_tag
    );
    assert!(
        stdout.contains(&format!("\"path\": {:?}", route.path)),
        "generated client must use active computed-read path {}; client:\n{stdout}",
        route.path
    );
}

#[test]
fn client_typescript_reports_project_diagnostics() {
    let root = temp_project_uncommitted("surface-client-typescript-bad-check", |root| {
        write(root, "marrow.json", support::native_config());
        write(root, "src/app.mw", "module app\npub fn broken(\n");
    });

    let output = marrow(&[
        "client",
        "typescript",
        root.to_str().expect("project path utf8"),
    ]);

    assert_eq!(output.status.code(), Some(1), "{output:?}");
    assert!(
        output.stdout.is_empty(),
        "failed check should not print a partial client"
    );
    let stderr = String::from_utf8(output.stderr).expect("stderr utf8");
    assert!(stderr.contains("parse."), "{stderr}");
}

#[test]
fn client_help_advertises_top_level_command() {
    let output = marrow(&["client", "--help"]);

    assert_eq!(output.status.code(), Some(0), "{output:?}");
    let stdout = String::from_utf8(output.stdout).expect("stdout utf8");
    assert!(stdout.contains("marrow client typescript <projectdir>"));
    assert!(
        !stdout.contains("marrow surface"),
        "client help should not advertise removed surface commands: {stdout}"
    );
}

#[test]
fn client_typescript_usage_failures_exit_two() {
    let output = marrow(&["client", "typescript"]);

    assert_eq!(output.status.code(), Some(2), "{output:?}");
    assert!(output.stdout.is_empty(), "{output:?}");
    let stderr = String::from_utf8(output.stderr).expect("stderr utf8");
    assert!(stderr.contains("missing project directory"), "{stderr}");
}

#[test]
fn client_typescript_generated_client_runs_against_live_surface_server() {
    let Some(node) = node_with_type_stripping() else {
        if std::env::var_os("CI").is_some() || std::env::var_os("MARROW_TEST_NODE").is_some() {
            panic!("generated TypeScript client E2E requires Node with --experimental-strip-types");
        }
        eprintln!("skipping generated TypeScript client E2E; compatible node not found");
        return;
    };
    let root = temp_project("surface-client-typescript-e2e", |root| {
        write(root, "marrow.json", support::native_config());
        write(root, "src/app.mw", CLIENT_SURFACE_SOURCE);
    });
    let seed = marrow(&["run", "--entry", "app::seed", root.to_str().unwrap()]);
    assert_eq!(seed.status.code(), Some(0), "seed: {seed:?}");

    let check = marrow(&["check", "--format", "json", root.to_str().unwrap()]);
    assert_eq!(check.status.code(), Some(0), "check: {check:?}");
    let report = support::json(check.stdout);
    let ids = surface_ids(&report);

    let client = marrow(&[
        "client",
        "typescript",
        root.to_str().expect("project path utf8"),
    ]);
    assert_eq!(client.status.code(), Some(0), "client: {client:?}");
    assert!(client.stderr.is_empty(), "client: {client:?}");
    let app = support::temp_dir("surface-client-typescript-e2e-app");
    write(
        &app,
        "marrow-client.ts",
        &String::from_utf8(client.stdout).expect("client utf8"),
    );
    write(&app, "app.ts", &generated_client_app(&ids));

    {
        let (_server, addr) = spawn_surface_server_with_args(&root, &["--write"]);
        let output = Command::new(node)
            .arg("--experimental-strip-types")
            .arg("--no-warnings")
            .arg(app.join("app.ts"))
            .current_dir(&app)
            .env("MARROW_SURFACE_BASE_URL", format!("http://{addr}"))
            .output()
            .expect("run generated client app");

        assert_eq!(
            output.status.code(),
            Some(0),
            "generated client app failed\nstdout:\n{}\nstderr:\n{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        );
        assert_eq!(
            String::from_utf8(output.stdout)
                .expect("app stdout utf8")
                .trim(),
            "generated-client-e2e-ok"
        );
    }

    let recover = marrow(&[
        "data",
        "recover",
        "--format",
        "json",
        root.to_str().expect("project path utf8"),
    ]);
    assert_eq!(recover.status.code(), Some(0), "recover: {recover:?}");

    let describe = marrow(&[
        "run",
        "--entry",
        "app::describe",
        "--arg",
        "id=1",
        "--format",
        "json",
        root.to_str().expect("project path utf8"),
    ]);
    assert_eq!(describe.status.code(), Some(0), "describe: {describe:?}");
    let envelope = support::json(describe.stdout);
    assert_eq!(envelope["result"]["kind"], "value", "{envelope}");
    assert_eq!(envelope["result"]["value"]["kind"], "string", "{envelope}");
    assert_eq!(
        envelope["result"]["value"]["value"], "The Dispossessed|Ursula Le Guin",
        "{envelope}"
    );

    let integrity = marrow(&[
        "data",
        "integrity",
        "--format",
        "json",
        root.to_str().expect("project path utf8"),
    ]);
    assert_eq!(integrity.status.code(), Some(0), "integrity: {integrity:?}");
}

struct SurfaceClientIds {
    store_catalog_id: String,
    title_catalog_id: String,
    author_catalog_id: String,
}

fn node_with_type_stripping() -> Option<PathBuf> {
    let candidates = std::env::var_os("MARROW_TEST_NODE")
        .map(PathBuf::from)
        .into_iter()
        .chain(std::env::var_os("PATH").into_iter().flat_map(|path| {
            std::env::split_paths(&path)
                .map(|dir| dir.join("node"))
                .collect::<Vec<_>>()
        }));
    for candidate in candidates {
        let Ok(output) = Command::new(&candidate).arg("--help").output() else {
            continue;
        };
        let help = String::from_utf8_lossy(&output.stdout);
        if output.status.success() && help.contains("--experimental-strip-types") {
            return Some(candidate);
        }
    }
    None
}

fn surface_ids(report: &Value) -> SurfaceClientIds {
    let create_route = route_by_alias(report, "create");
    let create = create_descriptor(report, &create_route.operation_tag);
    SurfaceClientIds {
        store_catalog_id: create["store_catalog_id"]
            .as_str()
            .expect("create store catalog id")
            .to_string(),
        title_catalog_id: create_field_catalog_id(create, "title"),
        author_catalog_id: create_field_catalog_id(create, "author"),
    }
}

fn generated_client_app(ids: &SurfaceClientIds) -> String {
    format!(
        r#"import assert from "node:assert/strict";
import {{ createClient }} from "./marrow-client.ts";

const ids = {{
  store: {store},
  title: {title},
  author: {author},
}};
const client = createClient({{
  baseUrl: process.env.MARROW_SURFACE_BASE_URL,
}});

const key = (id) => ({{
  store_catalog_id: ids.store,
  keys: [{{ kind: "int", value: id }}],
}});
const field = (record, label) => {{
  const found = record.fields.find((item) => item.render_label === label);
  assert.ok(found, `missing field ${{label}}`);
  return found.value;
}};
const get = async (id) => client.app.Books.get({{ identity: key(id) }});

const seeded = await get(1);
assert.equal(seeded.result.kind, "record");
assert.deepEqual(field(seeded.result.record, "title"), {{
  kind: "string",
  value: "Dune",
}});

const staleAfterCreate = await client.app.Books.byAuthor({{
  exact_keys: [{{ kind: "string", value: "Frank Herbert" }}],
  limit: 1,
}});
assert.ok(staleAfterCreate.result.page.next);

const created = await client.app.Books.create({{
  identity: key(3n),
  fields: [
    {{
      catalog_id: ids.title,
      value: {{ kind: "string", value: "Children of Dune" }},
    }},
    {{
      catalog_id: ids.author,
      value: {{ kind: "string", value: "Frank Herbert" }},
    }},
  ],
}});
assert.equal(created.result.kind, "created");
assert.deepEqual(field(created.result.record, "title"), {{
  kind: "string",
  value: "Children of Dune",
}});
await assert.rejects(
  () =>
    client.app.Books.byAuthor({{
      exact_keys: [{{ kind: "string", value: "Frank Herbert" }}],
      limit: 10,
      cursor: staleAfterCreate.result.page.next,
    }}),
  (error) => error.code === "surface.stale_cursor",
);

const staleAfterUpdate = await client.app.Books.byAuthor({{
  exact_keys: [{{ kind: "string", value: "Frank Herbert" }}],
  limit: 1,
}});
assert.ok(staleAfterUpdate.result.page.next);

const updated = await client.app.Books.update({{
  identity: key(1),
  fields: [
    {{
      catalog_id: ids.author,
      value: {{ kind: "string", value: "Ursula Le Guin" }},
    }},
  ],
}});
assert.equal(updated.result.kind, "updated");
const updatedRead = await get(1);
assert.deepEqual(field(updatedRead.result.record, "author"), {{
  kind: "string",
  value: "Ursula Le Guin",
}});
await assert.rejects(
  () =>
    client.app.Books.byAuthor({{
      exact_keys: [{{ kind: "string", value: "Frank Herbert" }}],
      limit: 10,
      cursor: staleAfterUpdate.result.page.next,
    }}),
  (error) => error.code === "surface.stale_cursor",
);

const frank = await client.app.Books.byAuthor({{
  exact_keys: [{{ kind: "string", value: "Frank Herbert" }}],
  limit: 10,
}});
assert.equal(frank.result.kind, "page");
assert.deepEqual(
  frank.result.page.rows.map((record) => field(record, "title").value),
  ["Dune Messiah", "Children of Dune"],
);

const staleAfterAction = await client.app.Books.byAuthor({{
  exact_keys: [{{ kind: "string", value: "Frank Herbert" }}],
  limit: 1,
}});
assert.ok(staleAfterAction.result.page.next);

const retitled = await client.app.Books.retitle({{
  arguments: [
    {{ name: "id", value: {{ kind: "int", value: "1" }} }},
    {{ name: "title", value: {{ kind: "string", value: "The Dispossessed" }} }},
  ],
}});
assert.equal(retitled.result.kind, "action");
assert.deepEqual(retitled.result.result.value, {{
  kind: "string",
  value: "The Dispossessed",
}});
const retitledRead = await get(1);
assert.deepEqual(field(retitledRead.result.record, "title"), {{
  kind: "string",
  value: "The Dispossessed",
}});
const described = await client.app.Books.describe({{
  arguments: [{{ name: "id", value: {{ kind: "int", value: "1" }} }}],
}});
assert.equal(described.result.kind, "computed_read");
assert.deepEqual(described.result.result.value, {{
  kind: "string",
  value: "The Dispossessed|Ursula Le Guin",
}});
await assert.rejects(
  () =>
    client.app.Books.byAuthor({{
      exact_keys: [{{ kind: "string", value: "Frank Herbert" }}],
      limit: 10,
      cursor: staleAfterAction.result.page.next,
    }}),
  (error) => error.code === "surface.stale_cursor",
);

const staleAfterDelete = await client.app.Books.byAuthor({{
  exact_keys: [{{ kind: "string", value: "Frank Herbert" }}],
  limit: 1,
}});
assert.ok(staleAfterDelete.result.page.next);

const deleted = await client.app.Books.delete({{ identity: key(3) }});
assert.equal(deleted.result.kind, "deleted");
await assert.rejects(() => get(3), (error) => error.code === "surface.absent");
await assert.rejects(
  () =>
    client.app.Books.byAuthor({{
      exact_keys: [{{ kind: "string", value: "Frank Herbert" }}],
      limit: 10,
      cursor: staleAfterDelete.result.page.next,
    }}),
  (error) => error.code === "surface.stale_cursor",
);

await assert.rejects(
  () => get(Number.MAX_SAFE_INTEGER + 1),
  /safe integers/,
);

console.log("generated-client-e2e-ok");
"#,
        store = serde_json::to_string(&ids.store_catalog_id).expect("store id json"),
        title = serde_json::to_string(&ids.title_catalog_id).expect("title id json"),
        author = serde_json::to_string(&ids.author_catalog_id).expect("author id json"),
    )
}
